apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minimart
resources:
  - api-deployment.yaml
  - web-deployment.yaml
  - postgres.yaml
  - redis.yaml
  - opensearch.yaml
  - secrets.yaml
